### ISSUE TITLE
Crash in Commit RPC

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#568]
When running on the DDN DGX box, the following is seen when the dotscience committer tries to send commit RPCs to the local dotmesh:

```
2018/09/07 15:16:34 http: panic serving 172.18.0.1:46710: interface conversion: map[string]interface {} is not error: missing method Error
goroutine 73036 [running]:
net/http.(*conn).serve.func1(0xc4202c2f00)
        GOROOT/src/net/http/server.go:1726 +0xd0
panic(0xd65e00, 0xc42313ca40)
        GOROOT/src/runtime/panic.go:502 +0x229
main.maybeError(0xc4224c2420, 0xc422aff3f8, 0x24)
        cmd/dotmesh-server/rpc.go:976 +0x11e
main.(*DotmeshRPC).Commit(0xc42013ec00, 0xc4202c6b00, 0xc422d80e60, 0xc422aaedb0, 0x0, 0x0)
        cmd/dotmesh-server/rpc.go:860 +0x62a
reflect.Value.call(0xc4202e4a00, 0xc4224fe178, 0x13, 0xe995a8, 0x4, 0xc422b65900, 0x4, 0x4, 0xcce8c0, 0xe701a0, ...)
        GOROOT/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4202e4a00, 0xc4224fe178, 0x13, 0xc422b65900, 0x4, 0x4, 0x0, 0x410299, 0x30)
        GOROOT/src/reflect/value.go:308 +0xa4
github.com/dotmesh-io/dotmesh/vendor/github.com/gorilla/rpc/v2.(*Server).ServeHTTP(0xc4224ea5a0, 0xf9ebe0, 0xc4230b69e0, 0xc4202c6b00)
        vendor/github.com/gorilla/rpc/v2/server.go:195 +0x45c
main.(*AuthHandler).ServeHTTP(0xc42013fee0, 0xf9ebe0, 0xc4230b69e0, 0xc4202c6700)
        cmd/dotmesh-server/auth_handler.go:48 +0x3cc
main.Instrument.func1.1(0xf9eee0, 0xc4230b82a0, 0xc4202c6700)
        cmd/dotmesh-server/http.go:251 +0x120
net/http.HandlerFunc.ServeHTTP(0xc42013ff00, 0xf9eee0, 0xc4230b82a0, 0xc4202c6700)
        GOROOT/src/net/http/server.go:1947 +0x44
github.com/dotmesh-io/dotmesh/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42021e620, 0xf9eee0, 0xc4230b82a0, 0xc4202c6700)
        vendor/github.com/gorilla/mux/mux.go:162 +0xed
net/http.serverHandler.ServeHTTP(0xc42014b860, 0xf9eee0, 0xc4230b82a0, 0xc4202c6500)
        GOROOT/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4202c2f00, 0xf9ff20, 0xc4226fa480)
        GOROOT/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        GOROOT/src/net/http/server.go:2795 +0x27b
```

**Comment by rusenask** [comment]
already fixed by @alaric-dotmesh
