### ISSUE TITLE
Dotmesh sometimes crashes when starting up runner tasks

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#595]
Anecdotally, Dotmesh has been crashing when restarting Jupyter, but it's also visible with `ds run`; frequently, a run start fails and the dotmesh container is observed to only be a few seconds old afterwards.

On Alaric's machine, this is also visible as #594 - the latter may be being caused by Dotmesh restarting and the container `dm` is trying to do a DNS lookup for therefore not being available; it segfaulting rather than saying "domain not found" is still a bug, however!

**Comment by lukemarsden** [comment]
I've also seen this when doing the following:

1. Create datasets and attach them to project, but forget to put any files in them yet
2. Start Jupyter
3. Drag some files into one or more of the datasets
4. Stop Jupyter, hoping to force things to reconcile despite the obvious divergence
5. Start Jupyter again <-- here you get errors in the log about "cannot connect to dotmesh on the runner" which I interpret to mean "dotmesh has crashed and is restarting, that's why dm can't connect"

**Comment by alaric-dotmesh** [comment]
I have lost the ability to reproduce this in my testbed - it was doing it pretty consistently yesterday and I've changed nothing :'-( It's not fair!

I can't try the Jupyter case in this testbed due to various other issues!

**Comment by alaric-dotmesh** [comment]
Caught one!

```
2018/11/13 16:19:32 <transition> aa69050d-9799-4428-574a-d81510150da5 to pullInitiatorState requesting (from active waiting, 0.01s ago)
2018/11/13 16:19:32 [updateEtcdAboutSnapshots] successfully set new snaps for aa69050d-9799-4428-574a-d81510150da5 on 547f5ab5f9a9a14d
2018/11/13 16:19:32 [Related] Containers related to volume admin/combined-houses: []
2018/11/13 16:19:33 [applyPath] applying path types.PathToTopLevelFilesystem{TopLevelFilesystemId:"aa69050d-9799-4428-574a-d81510150da5", TopLevelFilesystemName:types.VolumeName{Namespace:"test", Name:"combined-houses"}, Clones:types.ClonesList{}}
2018/11/13 16:19:33 [applyPath,b] calling transferFn with fF=, fS=, tF=aa69050d-9799-4428-574a-d81510150da5, tS=
2018/11/13 16:19:33 [updateEtcdAboutTransfers] Received command main.TransferUpdate{Kind:0, Changes:main.TransferPollResult{TransferRequestId:"0f9d0811-1818-4438-6d2d-3e7fdc6e883b", Peer:"35.242.162.101", User:"test", ApiKey:"password", Direction:"pull", LocalNamespace:"admin", LocalName:"combined-houses", LocalBranchName:"", RemoteNamespace:"test", RemoteName:"combined-houses", RemoteBranchName:"", FilesystemId:"", InitiatorNodeId:"547f5ab5f9a9a14d", PeerNodeId:"", StartingCommit:"", TargetCommit:"", Index:1, Total:1, Status:"syncing metadata", NanosecondsElapsed:0, Size:0, Sent:0, Message:""}, GetResult:(chan main.TransferPollResult)(nil)}
2018/11/13 16:19:33 [updateEtcdAboutTransfers] pollResult = main.TransferPollResult{TransferRequestId:"0f9d0811-1818-4438-6d2d-3e7fdc6e883b", Peer:"35.242.162.101", User:"test", ApiKey:"password", Direction:"pull", LocalNamespace:"admin", LocalName:"combined-houses", LocalBranchName:"", RemoteNamespace:"test", RemoteName:"combined-houses", RemoteBranchName:"", FilesystemId:"", InitiatorNodeId:"547f5ab5f9a9a14d", PeerNodeId:"", StartingCommit:"", TargetCommit:"", Index:1, Total:1, Status:"syncing metadata", NanosecondsElapsed:0, Size:0, Sent:0, Message:""}
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] starting: aa69050d-9799-4428-574a-d81510150da5"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] acquired lock: aa69050d-9799-4428-574a-d81510150da5"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] reusing fsMachine for aa69050d-9799-4428-574a-d81510150da5"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] starting: aa69050d-9799-4428-574a-d81510150da5"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] acquired lock: aa69050d-9799-4428-574a-d81510150da5"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] reusing fsMachine for aa69050d-9799-4428-574a-d81510150da5"
2018/11/13 16:19:33 [retryPull] from (, ) to (aa69050d-9799-4428-574a-d81510150da5, 2238fc4a-fc8c-434f-4e5d-2ab5dba34589)
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] starting: a3daed54-adb9-49c1-6140-cf8e9510b79e"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] acquired lock: a3daed54-adb9-49c1-6140-cf8e9510b79e"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] starting: a3daed54-adb9-49c1-6140-cf8e9510b79e"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] acquired lock: a3daed54-adb9-49c1-6140-cf8e9510b79e"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] initializing new fsMachine for a3daed54-adb9-49c1-6140-cf8e9510b79e"
time="2018-11-13T16:19:33Z" level=info msg="[initFilesystemMachine] initializing new fsMachine for a3daed54-adb9-49c1-6140-cf8e9510b79e"
2018/11/13 16:19:33 [run:a3daed54-adb9-49c1-6140-cf8e9510b79e] INIT
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc073a7]

goroutine 849 [running]:
main.(*fsMachine).retryPull(0xc42270c700, 0x0, 0x0, 0x0, 0x0, 0xc423348e10, 0x24, 0xc422a32120, 0x24, 0xc422b5a7b6, ...)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/pullinitiatorstate.go:416 +0x927
main.pullInitiatorState.func1(0xc42270c700, 0x0, 0x0, 0x0, 0x0, 0xc423348e10, 0x24, 0x0, 0x0, 0xc422b5a7b6, ...)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/pullinitiatorstate.go:87 +0xd1
main.(*fsMachine).applyPath(0xc42270c700, 0xc423348e10, 0x24, 0xc422a392a0, 0x4, 0xc422a392b0, 0xf, 0x14e4170, 0x0, 0x0, ...)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/transfers.go:174 +0x2a5
main.pullInitiatorState(0xc42270c700, 0xf0c608)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/pullinitiatorstate.go:82 +0xc5f
main.(*fsMachine).run.func1(0xc42270c700)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/statemachines.go:135 +0x3b
created by main.(*fsMachine).run
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/statemachines.go:133 +0x33e
2018/11/13 16:19:33 [run:a3daed54-adb9-49c1-6140-cf8e9510b79e] reading from external requests
2018/11/13 16:19:33 <transition> a3daed54-adb9-49c1-6140-cf8e9510b79e to discovering loading (from discovering , 0.00s ago)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc073a7]

goroutine 849 [running]:
main.(*fsMachine).retryPull(0xc42270c700, 0x0, 0x0, 0x0, 0x0, 0xc423348e10, 0x24, 0xc422a32120, 0x24, 0xc422b5a7b6, ...)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/pullinitiatorstate.go:416 +0x927
main.pullInitiatorState.func1(0xc42270c700, 0x0, 0x0, 0x0, 0x0, 0xc423348e10, 0x24, 0x0, 0x0, 0xc422b5a7b6, ...)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/pullinitiatorstate.go:87 +0xd1
main.(*fsMachine).applyPath(0xc42270c700, 0xc423348e10, 0x24, 0xc422a392a0, 0x4, 0xc422a392b0, 0xf, 0x14e4170, 0x0, 0x0, ...)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/transfers.go:174 +0x2a5
main.pullInitiatorState(0xc42270c700, 0xf0c608)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/pullinitiatorstate.go:82 +0xc5f
main.(*fsMachine).run.func1(0xc42270c700)
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/statemachines.go:135 +0x3b
created by main.(*fsMachine).run
	/root/go/src/github.com/dotmesh-io/dotmesh/cmd/dotmesh-server/statemachines.go:133 +0x33e
+ sleep 1
```

Those line numbers should make sense in relation to:


```
Current remote: localadmin (use 'dm remote -v' to list and 'dm remote switch' to switch)

Client:
	Version: master-a519bef
Server:
	Version: master-a519bef
```

**Comment by alaric-dotmesh** [comment]
At the same time, this is what appeared at the frontend:

```
2018-11-13 16:19:32.109 Z agent-stdout: exec: dm clone,--stash-on-divergence,dotscience-hub,test/combined-houses [object Object]
2018-11-13 16:19:33.930 Z agent-stderr: error inspecting dotmesh state, got 
2018-11-13 16:19:34.674 Z agent-stdout: INSTALLING DOTMESH: waiting
2018-11-13 16:19:34.676 Z agent-stdout: Running docker-compose with params: --no-ansi,-f,/tmp/dotmeshComposeFolder1181013-1-1bim0na.5u0b/docker-compose.yaml,-p,dotmesh,up,-d
2018-11-13 16:19:34.773 Z agent-stdout: Pulling admin/combined-houses from dotscience-hub:test/combined-houses
2018-11-13 16:19:34.773 Z agent-stdout: Calculating...
2018-11-13 16:19:34.773 Z agent-stdout: Got error, trying again: Unable to connect to any of the addresses attempted: [dotmesh-server-inner], errs: [Post http://dotmesh-server-inner:32607/rpc: dial tcp 172.22.0.3:32607: connect: connection refused Post http://dotmesh-server-inner:6969/rpc: dial tcp 172.22.0.3:6969: connect: connection refused]
2018-11-13 16:19:34.773 Z agent-stdout: 
2018-11-13 16:19:34.773 Z agent-stdout:  0 B / ? 
2018-11-13 16:19:34.773 Z agent-stdout:  0 B / ?  ? MiB/s (0/0)
2018-11-13 16:19:34.773 Z agent-stdout:  0 B / ?  ? MiB/s (0/0)
2018-11-13 16:19:34.773 Z agent-stdout:  0 B / ?  ? MiB/s (0/0)
2018-11-13 16:19:34.773 Z agent-stdout:  0 B / ?  ? MiB/s (0/0)
2018-11-13 16:19:34.773 Z agent-stderr: fatal error: unexpected signal during runtime execution
2018-11-13 16:19:34.773 Z agent-stderr: [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f05eeaaf448]
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: runtime stack:
2018-11-13 16:19:34.773 Z agent-stderr: runtime.throw(0xe12b25, 0x2a)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/runtime/panic.go:616 +0x81
2018-11-13 16:19:34.773 Z agent-stderr: runtime.sigpanic()
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/runtime/signal_unix.go:372 +0x28e
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 51 [syscall]:
2018-11-13 16:19:34.773 Z agent-stderr: runtime.cgocall(0xb70fee, 0xc4200415f8, 0x29)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/runtime/cgocall.go:128 +0x64 fp=0xc4200415b8 sp=0xc420041580 pc=0x402384
2018-11-13 16:19:34.773 Z agent-stderr: net._C2func_getaddrinfo(0xc4201c9e20, 0x0, 0xc420295ef0, 0xc42000e940, 0x0, 0x0, 0x0)
2018-11-13 16:19:34.773 Z agent-stderr: 	_cgo_gotypes.go:92 +0x55 fp=0xc4200415f8 sp=0xc4200415b8 pc=0x5b6255
2018-11-13 16:19:34.773 Z agent-stderr: net.cgoLookupIPCNAME.func1(0xc4201c9e20, 0x0, 0xc420295ef0, 0xc42000e940, 0x15, 0x15, 0xc420204000)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/cgo_unix.go:149 +0x13b fp=0xc420041640 sp=0xc4200415f8 pc=0x5bcf4b
2018-11-13 16:19:34.773 Z agent-stderr: net.cgoLookupIPCNAME(0xc4201c9e00, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/cgo_unix.go:149 +0x174 fp=0xc420041738 sp=0xc420041640 pc=0x5b78c4
2018-11-13 16:19:34.773 Z agent-stderr: net.cgoIPLookup(0xc420342420, 0xc4201c9e00, 0x14)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/cgo_unix.go:201 +0x4d fp=0xc4200417c8 sp=0xc420041738 pc=0x5b7f8d
2018-11-13 16:19:34.773 Z agent-stderr: runtime.goexit()
2018-11-13 16:19:34.773 Z agent-stderr: 	bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_static_stripped/stdlib~/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200417d0 sp=0xc4200417c8 pc=0x458521
2018-11-13 16:19:34.773 Z agent-stderr: created by net.cgoLookupIP
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/cgo_unix.go:211 +0xaf
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 1 [select]:
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/pkg/client.(*DotmeshAPI).PollTransfer(0xc420294ea0, 0xc4201bb950, 0x24, 0xed7320, 0xc42000e018, 0x0, 0x0)
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/api.go:815 +0x37e
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/cmd/dm/pkg/commands.NewCmdClone.func1.1(0xedf8a0, 0xc4202a1110)
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/pkg/commands/clone.go:53 +0x1af
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/cmd/dm/pkg/commands.runHandlingError(0xc4201a7ca0)
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/pkg/commands/utils.go:89 +0x2b
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/cmd/dm/pkg/commands.NewCmdClone.func1(0xc4202a4b40, 0xc420294c30, 0x2, 0x3)
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/pkg/commands/clone.go:31 +0x79
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/cmd/dm/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202a4b40, 0xc420294b70, 0x3, 0x3, 0xc4202a4b40, 0xc420294b70)
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/vendor/github.com/spf13/cobra/command.go:636 +0x234
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/cmd/dm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x12c17a0, 0xc4202a4000, 0xc42029fd40, 0xc4200b18c0)
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/vendor/github.com/spf13/cobra/command.go:722 +0x2d4
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/cmd/dm/vendor/github.com/spf13/cobra.(*Command).Execute(0x12c17a0, 0xc42010fee0, 0xc4201a7f58)
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/vendor/github.com/spf13/cobra/command.go:681 +0x2b
2018-11-13 16:19:34.773 Z agent-stderr: main.main()
2018-11-13 16:19:34.773 Z agent-stderr: 	cmd/dm/dotmesh.go:40 +0x1f9
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 5 [chan receive]:
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x12fd6e0)
2018-11-13 16:19:34.773 Z agent-stderr: 	vendor/github.com/golang/glog/glog.go:882 +0x8b
2018-11-13 16:19:34.773 Z agent-stderr: created by github.com/dotmesh-io/dotmesh/vendor/github.com/golang/glog.init.0
2018-11-13 16:19:34.773 Z agent-stderr: 	vendor/github.com/golang/glog/glog.go:410 +0x203
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 7 [syscall]:
2018-11-13 16:19:34.773 Z agent-stderr: os/signal.signal_recv(0xc4200407c8)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/runtime/sigqueue.go:139 +0xa6
2018-11-13 16:19:34.773 Z agent-stderr: os/signal.loop()
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/os/signal/signal_unix.go:22 +0x22
2018-11-13 16:19:34.773 Z agent-stderr: created by os/signal.init.0
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/os/signal/signal_unix.go:28 +0x41
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 15 [select]:
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Transport).getConn(0x12c0e20, 0xc420295dd0, 0x0, 0xc4201bb9e0, 0x4, 0xc4201c9e00, 0x1a, 0x0, 0x0, 0xc420063358)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:962 +0x558
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Transport).RoundTrip(0x12c0e20, 0xc420020a00, 0x12c0e20, 0x0, 0x0)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:409 +0x632
2018-11-13 16:19:34.773 Z agent-stderr: net/http.send(0xc420020a00, 0xed70c0, 0x12c0e20, 0x0, 0x0, 0x0, 0xc42000e930, 0x0, 0xc4200636b8, 0x1)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/client.go:252 +0x185
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Client).send(0x12fd040, 0xc420020a00, 0x0, 0x0, 0x0, 0xc42000e930, 0x0, 0x1, 0xc420063788)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/client.go:176 +0xfa
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Client).Do(0x12fd040, 0xc420020a00, 0x5, 0xc4201c98e0, 0x20)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/client.go:615 +0x28d
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/pkg/client.(*JsonRpcClient).reallyCallRemote(0xc420063c58, 0xedd320, 0xc420295cb0, 0xe00205, 0xf, 0x0, 0x0, 0xc84880, 0xc4201c7cec, 0xc4201bb9e0, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/client.go:112 +0x505
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/pkg/client.DeduceUrl(0xedd2e0, 0xc4203420c0, 0xc4202ae6d0, 0x1, 0x1, 0xdfbdac, 0x8, 0xc4201c76c8, 0x5, 0xc4201c98e0, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/client.go:167 +0x231
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/pkg/client.(*JsonRpcClient).CallRemote(0xc4202d4500, 0xedd2e0, 0xc4203420c0, 0xe04fcb, 0x16, 0xcb2000, 0xc4202ae6c0, 0xceb020, 0xc4202b0750, 0x1, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/client.go:65 +0xef
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/pkg/client.(*DotmeshAPI).CallRemote(0xc420294ea0, 0xedd2e0, 0xc4203420c0, 0xe04fcb, 0x16, 0xcb2000, 0xc4202ae6c0, 0xceb020, 0xc4202b0750, 0xc420041658, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/api.go:88 +0xcc
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/pkg/client.(*DotmeshAPI).PollTransfer.func1(0x4a817c800, 0xed7320, 0xc42000e018, 0xc4201bb950, 0x24, 0xc420294ea0, 0xedd2e0, 0xc4203420c0, 0xc420342060)
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/api.go:796 +0x103
2018-11-13 16:19:34.773 Z agent-stderr: created by github.com/dotmesh-io/dotmesh/pkg/client.(*DotmeshAPI).PollTransfer
2018-11-13 16:19:34.773 Z agent-stderr: 	pkg/client/api.go:790 +0x24d
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 44 [runnable]:
2018-11-13 16:19:34.773 Z agent-stderr: github.com/dotmesh-io/dotmesh/vendor/gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).refresher(0xc4202e0dc0)
2018-11-13 16:19:34.773 Z agent-stderr: 	vendor/gopkg.in/cheggaaa/pb.v1/pb.go:493 +0xf5
2018-11-13 16:19:34.773 Z agent-stderr: created by github.com/dotmesh-io/dotmesh/vendor/gopkg.in/cheggaaa/pb%2ev1.(*ProgressBar).Start
2018-11-13 16:19:34.773 Z agent-stderr: 	vendor/gopkg.in/cheggaaa/pb.v1/pb.go:124 +0xc0
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 16 [select]:
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Resolver).LookupIPAddr(0x12fbe00, 0xedd320, 0xc420295cb0, 0xc4201c9e00, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/lookup.go:212 +0x50d
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Resolver).internetAddrList(0x12fbe00, 0xedd320, 0xc420295cb0, 0xdf7db5, 0x3, 0xc4201c9e00, 0x1a, 0x0, 0x0, 0x0, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/ipsock.go:293 +0x5c4
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Resolver).resolveAddrList(0x12fbe00, 0xedd320, 0xc420295cb0, 0xdf8326, 0x4, 0xdf7db5, 0x3, 0xc4201c9e00, 0x1a, 0x0, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/dial.go:193 +0x50c
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Dialer).DialContext(0xc4200720c0, 0xedd320, 0xc420295cb0, 0xdf7db5, 0x3, 0xc4201c9e00, 0x1a, 0x0, 0x0, 0x0, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/dial.go:375 +0x22b
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Dialer).DialContext-fm(0xedd320, 0xc420295cb0, 0xdf7db5, 0x3, 0xc4201c9e00, 0x1a, 0xc420052ae8, 0x63a7f9, 0xc420295cb0, 0xd01e80)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:46 +0x73
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Transport).dial(0x12c0e20, 0xedd320, 0xc420295cb0, 0xdf7db5, 0x3, 0xc4201c9e00, 0x1a, 0x445891, 0x4452bf, 0x1a, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:898 +0x20d
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Transport).dialConn(0x12c0e20, 0xedd320, 0xc420295cb0, 0x0, 0xc4201bb9e0, 0x4, 0xc4201c9e00, 0x1a, 0x1, 0x0, ...)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:1143 +0x317
2018-11-13 16:19:34.773 Z agent-stderr: net/http.(*Transport).getConn.func4(0x12c0e20, 0xedd320, 0xc420295cb0, 0xc420295e00, 0xc42008ab40)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:957 +0x78
2018-11-13 16:19:34.773 Z agent-stderr: created by net/http.(*Transport).getConn
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/http/transport.go:956 +0x363
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.773 Z agent-stderr: goroutine 50 [select]:
2018-11-13 16:19:34.773 Z agent-stderr: net.cgoLookupIP(0xedd260, 0xc420280a00, 0xc4201c9e00, 0x14, 0x0, 0x0, 0x0, 0xcb2000, 0xc4202ae6c0, 0xceb020)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/cgo_unix.go:212 +0x19f
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Resolver).lookupIP(0x12fbe00, 0xedd260, 0xc420280a00, 0xc4201c9e00, 0x14, 0xcb2000, 0xc420206f00, 0xc420204000, 0xc4202b0750, 0xc420041658)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/lookup_unix.go:95 +0x12d
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Resolver).(net.lookupIP)-fm(0xedd260, 0xc420280a00, 0xc4201c9e00, 0x14, 0x42a239, 0xc400000008, 0xc420204000, 0xc420280580, 0xc4200416a0)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/lookup.go:192 +0x56
2018-11-13 16:19:34.773 Z agent-stderr: net.glob..func10(0xedd260, 0xc420280a00, 0xc4202ae8d0, 0xc4201c9e00, 0x14, 0x0, 0xc42000e8f0, 0xc420295b30, 0xc420073e58, 0xc420295680)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/hook.go:19 +0x52
2018-11-13 16:19:34.773 Z agent-stderr: net.(*Resolver).LookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/net/lookup.go:206 +0xd8
2018-11-13 16:19:34.773 Z agent-stderr: internal/singleflight.(*Group).doCall(0x12fbdf0, 0xc42001f900, 0xc4201c9e00, 0x14, 0xc420295e90)
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/internal/singleflight/singleflight.go:95 +0x2e
2018-11-13 16:19:34.773 Z agent-stderr: created by internal/singleflight.(*Group).DoChan
2018-11-13 16:19:34.773 Z agent-stderr: 	GOROOT/src/internal/singleflight/singleflight.go:88 +0x2d0
2018-11-13 16:19:34.773 Z agent-stderr: 
2018-11-13 16:19:34.774 Z agent-stderr: error from running dm clone,--stash-on-divergence,dotscience-hub,test/combined-houses - 2
2018-11-13 16:19:34.774 Z agent-stderr: Failed to set up dots: 2
2018-11-13 16:19:34.774 Z agent-stderr: 2
Task FAILED: No run metadata was returned
```
