### ISSUE TITLE
[INTERRUPTION] TestS3Remote/ClonePushThenDeleteDot is hanging

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#623]
See, eg, https://gitlab.dotmesh.com/dotmesh/dotmesh-sync/-/jobs/141744

```
Jan 30 10:33:11 === RUN   TestS3Remote/ClonePushThenDeleteDot
Jan 30 10:33:11 RUNNING on cluster-15809385386370816-0-node-0: dm clone test-real-s3 test.dotmesh --local-name=volume_5
Jan 30 10:33:18 RUNNING on cluster-15809385386370816-0-node-0: docker run -i -v 'volume_5:/foo' --volume-driver dm gitlab-dawdler.local:80/busybox touch /foo/pushed-file.txt
Jan 30 10:33:19 RUNNING on cluster-15809385386370816-0-node-0: dm switch volume_5
Jan 30 10:33:19 RUNNING on cluster-15809385386370816-0-node-0: dm commit -m 'push this back to s3'
Jan 30 10:33:19 RUNNING on cluster-15809385386370816-0-node-0: dm push test-real-s3 volume_5
Jan 30 10:33:22 RUNNING on cluster-15809385386370816-0-node-0: dm dot delete volume_5
Jan 30 10:45:47 panic: test timed out after 15m0s
[...]
Jan 30 10:45:47 goroutine 358 [syscall, 13 minutes]:
Jan 30 10:45:47 syscall.Syscall6(0xf7, 0x1, 0x3a67, 0xc00032da68, 0x1000004, 0x0, 0x0, 0x20, 0xc0000bfba0, 0x0)
Jan 30 10:45:47 	/snap/go/3129/src/syscall/asm_linux_amd64.s:44 +0x5
Jan 30 10:45:47 os.(*Process).blockUntilWaitable(0xc000365050, 0x7, 0xc00032dbd0, 0xc000365050)
Jan 30 10:45:47 	/snap/go/3129/src/os/wait_waitid.go:31 +0x98
Jan 30 10:45:47 os.(*Process).wait(0xc000365050, 0xa4a8c0, 0x1, 0xc000172600)
Jan 30 10:45:47 	/snap/go/3129/src/os/exec_unix.go:22 +0x39
Jan 30 10:45:47 os.(*Process).Wait(0xc000365050, 0xb45208, 0xb45210, 0xb45200)
Jan 30 10:45:47 	/snap/go/3129/src/os/exec.go:125 +0x2b
Jan 30 10:45:47 os/exec.(*Cmd).Wait(0xc000375340, 0x0, 0x0)
Jan 30 10:45:47 	/snap/go/3129/src/os/exec/exec.go:465 +0x5b
Jan 30 10:45:47 os/exec.(*Cmd).Run(0xc000375340, 0x1, 0x1)
Jan 30 10:45:47 	/snap/go/3129/src/os/exec/exec.go:309 +0x5c
Jan 30 10:45:47 github.com/dotmesh-io/dotmesh/tests/vendor/github.com/dotmesh-io/citools.docker(0xc000373680, 0x22, 0xc000387480, 0x16, 0x0, 0x46, 0x0, 0x0, 0x0)
Jan 30 10:45:47 	/home/gitlab-runner/builds/65e3c702/2/dotmesh/dotmesh-sync/gopath/src/github.com/dotmesh-io/dotmesh/tests/vendor/github.com/dotmesh-io/citools/testtools.go:842 +0x607
Jan 30 10:45:47 github.com/dotmesh-io/dotmesh/tests/vendor/github.com/dotmesh-io/citools.RunOnNodeErr(0xc000373680, 0x22, 0xc000387480, 0x16, 0x8, 0xc000387480, 0x16, 0x3931ad7af1f74)
Jan 30 10:45:47 	/home/gitlab-runner/builds/65e3c702/2/dotmesh/dotmesh-sync/gopath/src/github.com/dotmesh-io/dotmesh/tests/vendor/github.com/dotmesh-io/citools/testtools.go:877 +0x145
Jan 30 10:45:47 github.com/dotmesh-io/dotmesh/tests.TestS3Remote.func8(0xc000314100)
Jan 30 10:45:47 	/home/gitlab-runner/builds/65e3c702/2/dotmesh/dotmesh-sync/gopath/src/github.com/dotmesh-io/dotmesh/tests/s3remote_test.go:187 +0x2e3
Jan 30 10:45:47 testing.tRunner(0xc000314100, 0xc000274560)
Jan 30 10:45:47 	/snap/go/3129/src/testing/testing.go:827 +0xbf
Jan 30 10:45:47 created by testing.(*T).Run
Jan 30 10:45:47 	/snap/go/3129/src/testing/testing.go:878 +0x35c
Jan 30 10:45:47 
```

**Comment by alaric-dotmesh** [comment]
Bug was in the test... fixed it.
